# Generated by Django 3.1.6 on 2021-09-04 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_activity', models.DateTimeField()),
                ('end_activity', models.DateTimeField()),
                ('activity', models.CharField(choices=[('Walking', 'Walking'), ('Running', 'Running'), ('Bike', 'Bike')], max_length=200)),
                ('distance', models.FloatField()),
                ('calories', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
